name: Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy
    runs-on: self-hosted
    environment: cloud

    steps:

    - name: Checkout
      uses: actions/checkout@v3
    
    - id: auth
      name: Authenticate to Google Cloud
      uses: google-github-actions/auth@v1
      with:
        credentials_json: ${{ secrets.GCP_SERVICE_ACCOUNT }}
    
    - name: Authenticate to GKE
      uses: 'google-github-actions/get-gke-credentials@v1'
      with:
        cluster_name: ${{ vars.GKE_CLUSTER }}
        location: ${{ vars.GKE_LOCATION }}

    - name: Deploy HELM3
      uses: WyriHaximus/github-action-helm3@v3
      with:
        exec: helm upgrade --install --wait --debug dev charts